/* Generated by scripts/generate-arcade-integration.ts. Do not edit by hand. */
export type {
  ArcadeAuthorizationResponse,
  ArcadeAuthorizationStatus,
  ArcadeCredentials,
  ArcadeToolOptions,
  ArcadeToolResult,
  MaybeHandle,
  ResolvableInput,
} from "@workflow/integrations-arcade";
export {
  arcade,
  createArcadeToolAction,
  createArcadeToolAtom,
} from "@workflow/integrations-arcade";
