/* Generated by scripts/generate-arcade-integration.ts. Do not edit by hand. */
import type { Action, Atom } from "@workflow/core";
import { z } from "zod";
import {
  type ArcadeToolOptions,
  type ArcadeToolResult,
  createArcadeToolAction,
  createArcadeToolAtom,
  type MaybeHandle,
} from "./arcade";

export const LINEAR_TOOL_VERSION = "3.4.0";

export type LinearJsonObject = Record<string, unknown>;
export type LinearToolOptions = ArcadeToolOptions;
export type LinearToolAction<Value = LinearJsonObject> = Action<
  ArcadeToolResult<Value>
>;
export type LinearToolAtom<Value = LinearJsonObject> = Atom<
  ArcadeToolResult<Value>
>;

type Resolvable<T> = MaybeHandle<T>;
const jsonObjectSchema: z.ZodType<Record<string, unknown>> = z
  .object({})
  .catchall(z.unknown());

export const linearStatusSchema = z.enum([
  "Backlog",
  "Planned",
  "Active",
  "Paused",
  "Completed",
  "Canceled",
]);
export type LinearStatus = z.infer<typeof linearStatusSchema>;

export const linearPrioritySchema = z.enum([
  "none",
  "urgent",
  "high",
  "medium",
  "low",
]);
export type LinearPriority = z.infer<typeof linearPrioritySchema>;

export const linearRelationTypeSchema = z.enum([
  "blocks",
  "blockedBy",
  "duplicate",
  "related",
]);
export type LinearRelationType = z.infer<typeof linearRelationTypeSchema>;

export const linearStateSchema = z.enum([
  "backlog",
  "planned",
  "started",
  "paused",
  "completed",
  "canceled",
]);
export type LinearState = z.infer<typeof linearStateSchema>;

export const linearHealthSchema = z.enum(["onTrack", "atRisk", "offTrack"]);
export type LinearHealth = z.infer<typeof linearHealthSchema>;

export const linearLookupBySchema = z.enum(["id", "name"]);
export type LinearLookupBy = z.infer<typeof linearLookupBySchema>;

export const linearGetProjectLookupBySchema = z.enum(["id", "slug_id", "name"]);
export type LinearGetProjectLookupBy = z.infer<
  typeof linearGetProjectLookupBySchema
>;

export const linearGetTeamLookupBySchema = z.enum(["id", "key", "name"]);
export type LinearGetTeamLookupBy = z.infer<typeof linearGetTeamLookupBySchema>;

export const linearCommentFilterSchema = z.enum([
  "only_quoted",
  "only_unquoted",
  "all",
]);
export type LinearCommentFilter = z.infer<typeof linearCommentFilterSchema>;

export const linearStateTypeSchema = z.enum([
  "triage",
  "backlog",
  "unstarted",
  "started",
  "completed",
  "canceled",
]);
export type LinearStateType = z.infer<typeof linearStateTypeSchema>;

export type AddCommentInput = {
  body: string;
  issue: string;
};
export type AddCommentOptions = LinearToolOptions & {
  body: Resolvable<string>;
  issue: Resolvable<string>;
};
const addCommentInputSchema: z.ZodType<AddCommentInput> = z.object({
  body: z.string(),
  issue: z.string(),
});
export function addComment(
  opts: AddCommentOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.AddComment",
    inputSchema: addCommentInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      body: opts.body,
      issue: opts.issue,
    },
  });
}

export type AddProjectCommentInput = {
  auto_accept_matches?: boolean;
  body: string;
  project: string;
  quoted_text?: string;
};
export type AddProjectCommentOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  body: Resolvable<string>;
  project: Resolvable<string>;
  quotedText?: Resolvable<string | undefined>;
};
const addProjectCommentInputSchema: z.ZodType<AddProjectCommentInput> =
  z.object({
    auto_accept_matches: z.boolean().optional(),
    body: z.string(),
    project: z.string(),
    quoted_text: z.string().optional(),
  });
export function addProjectComment(
  opts: AddProjectCommentOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.AddProjectComment",
    inputSchema: addProjectCommentInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      body: opts.body,
      project: opts.project,
      quoted_text: opts.quotedText,
    },
  });
}

export type AddProjectToInitiativeInput = {
  auto_accept_matches?: boolean;
  initiative: string;
  project: string;
};
export type AddProjectToInitiativeOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  initiative: Resolvable<string>;
  project: Resolvable<string>;
};
const addProjectToInitiativeInputSchema: z.ZodType<AddProjectToInitiativeInput> =
  z.object({
    auto_accept_matches: z.boolean().optional(),
    initiative: z.string(),
    project: z.string(),
  });
export function addProjectToInitiative(
  opts: AddProjectToInitiativeOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.AddProjectToInitiative",
    inputSchema: addProjectToInitiativeInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      initiative: opts.initiative,
      project: opts.project,
    },
  });
}

export type ArchiveInitiativeInput = {
  auto_accept_matches?: boolean;
  initiative: string;
};
export type ArchiveInitiativeOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  initiative: Resolvable<string>;
};
const archiveInitiativeInputSchema: z.ZodType<ArchiveInitiativeInput> =
  z.object({
    auto_accept_matches: z.boolean().optional(),
    initiative: z.string(),
  });
export function archiveInitiative(
  opts: ArchiveInitiativeOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.ArchiveInitiative",
    inputSchema: archiveInitiativeInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      initiative: opts.initiative,
    },
  });
}

export type ArchiveIssueInput = {
  issue: string;
};
export type ArchiveIssueOptions = LinearToolOptions & {
  issue: Resolvable<string>;
};
const archiveIssueInputSchema: z.ZodType<ArchiveIssueInput> = z.object({
  issue: z.string(),
});
export function archiveIssue(
  opts: ArchiveIssueOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.ArchiveIssue",
    inputSchema: archiveIssueInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      issue: opts.issue,
    },
  });
}

export type ArchiveProjectInput = {
  auto_accept_matches?: boolean;
  project: string;
};
export type ArchiveProjectOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  project: Resolvable<string>;
};
const archiveProjectInputSchema: z.ZodType<ArchiveProjectInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  project: z.string(),
});
export function archiveProject(
  opts: ArchiveProjectOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.ArchiveProject",
    inputSchema: archiveProjectInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      project: opts.project,
    },
  });
}

export type CreateInitiativeInput = {
  description?: string;
  name: string;
  status?:
    | "Backlog"
    | "Planned"
    | "Active"
    | "Paused"
    | "Completed"
    | "Canceled";
  target_date?: string;
};
export type CreateInitiativeOptions = LinearToolOptions & {
  description?: Resolvable<string | undefined>;
  name: Resolvable<string>;
  status?: Resolvable<
    | "Backlog"
    | "Planned"
    | "Active"
    | "Paused"
    | "Completed"
    | "Canceled"
    | undefined
  >;
  targetDate?: Resolvable<string | undefined>;
};
const createInitiativeInputSchema: z.ZodType<CreateInitiativeInput> = z.object({
  description: z.string().optional(),
  name: z.string(),
  status: z
    .enum(["Backlog", "Planned", "Active", "Paused", "Completed", "Canceled"])
    .optional(),
  target_date: z.string().optional(),
});
export function createInitiative(
  opts: CreateInitiativeOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.CreateInitiative",
    inputSchema: createInitiativeInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      description: opts.description,
      name: opts.name,
      status: opts.status,
      target_date: opts.targetDate,
    },
  });
}

export type CreateIssueInput = {
  assignee?: string;
  attachment_title?: string;
  attachment_url?: string;
  auto_accept_matches?: boolean;
  cycle?: string;
  description?: string;
  due_date?: string;
  estimate?: number;
  labels_to_add?: string[];
  parent_issue?: string;
  priority?: "none" | "urgent" | "high" | "medium" | "low";
  project?: string;
  state?: string;
  team: string;
  title: string;
};
export type CreateIssueOptions = LinearToolOptions & {
  assignee?: Resolvable<string | undefined>;
  attachmentTitle?: Resolvable<string | undefined>;
  attachmentUrl?: Resolvable<string | undefined>;
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  cycle?: Resolvable<string | undefined>;
  description?: Resolvable<string | undefined>;
  dueDate?: Resolvable<string | undefined>;
  estimate?: Resolvable<number | undefined>;
  labelsToAdd?: Resolvable<string[] | undefined>;
  parentIssue?: Resolvable<string | undefined>;
  priority?: Resolvable<
    "none" | "urgent" | "high" | "medium" | "low" | undefined
  >;
  project?: Resolvable<string | undefined>;
  state?: Resolvable<string | undefined>;
  team: Resolvable<string>;
  title: Resolvable<string>;
};
const createIssueInputSchema: z.ZodType<CreateIssueInput> = z.object({
  assignee: z.string().optional(),
  attachment_title: z.string().optional(),
  attachment_url: z.string().optional(),
  auto_accept_matches: z.boolean().optional(),
  cycle: z.string().optional(),
  description: z.string().optional(),
  due_date: z.string().optional(),
  estimate: z.number().int().optional(),
  labels_to_add: z.array(z.string()).optional(),
  parent_issue: z.string().optional(),
  priority: z.enum(["none", "urgent", "high", "medium", "low"]).optional(),
  project: z.string().optional(),
  state: z.string().optional(),
  team: z.string(),
  title: z.string(),
});
export function createIssue(
  opts: CreateIssueOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.CreateIssue",
    inputSchema: createIssueInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      assignee: opts.assignee,
      attachment_title: opts.attachmentTitle,
      attachment_url: opts.attachmentUrl,
      auto_accept_matches: opts.autoAcceptMatches,
      cycle: opts.cycle,
      description: opts.description,
      due_date: opts.dueDate,
      estimate: opts.estimate,
      labels_to_add: opts.labelsToAdd,
      parent_issue: opts.parentIssue,
      priority: opts.priority,
      project: opts.project,
      state: opts.state,
      team: opts.team,
      title: opts.title,
    },
  });
}

export type CreateIssueRelationInput = {
  issue: string;
  related_issue: string;
  relation_type: "blocks" | "blockedBy" | "duplicate" | "related";
};
export type CreateIssueRelationOptions = LinearToolOptions & {
  issue: Resolvable<string>;
  relatedIssue: Resolvable<string>;
  relationType: Resolvable<"blocks" | "blockedBy" | "duplicate" | "related">;
};
const createIssueRelationInputSchema: z.ZodType<CreateIssueRelationInput> =
  z.object({
    issue: z.string(),
    related_issue: z.string(),
    relation_type: z.enum(["blocks", "blockedBy", "duplicate", "related"]),
  });
export function createIssueRelation(
  opts: CreateIssueRelationOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.CreateIssueRelation",
    inputSchema: createIssueRelationInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      issue: opts.issue,
      related_issue: opts.relatedIssue,
      relation_type: opts.relationType,
    },
  });
}

export type CreateProjectInput = {
  auto_accept_matches?: boolean;
  content?: string;
  description?: string;
  lead?: string;
  name: string;
  start_date?: string;
  state?:
    | "backlog"
    | "planned"
    | "started"
    | "paused"
    | "completed"
    | "canceled";
  target_date?: string;
  team: string;
};
export type CreateProjectOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  content?: Resolvable<string | undefined>;
  description?: Resolvable<string | undefined>;
  lead?: Resolvable<string | undefined>;
  name: Resolvable<string>;
  startDate?: Resolvable<string | undefined>;
  state?: Resolvable<
    | "backlog"
    | "planned"
    | "started"
    | "paused"
    | "completed"
    | "canceled"
    | undefined
  >;
  targetDate?: Resolvable<string | undefined>;
  team: Resolvable<string>;
};
const createProjectInputSchema: z.ZodType<CreateProjectInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  content: z.string().optional(),
  description: z.string().optional(),
  lead: z.string().optional(),
  name: z.string(),
  start_date: z.string().optional(),
  state: z
    .enum(["backlog", "planned", "started", "paused", "completed", "canceled"])
    .optional(),
  target_date: z.string().optional(),
  team: z.string(),
});
export function createProject(
  opts: CreateProjectOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.CreateProject",
    inputSchema: createProjectInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      content: opts.content,
      description: opts.description,
      lead: opts.lead,
      name: opts.name,
      start_date: opts.startDate,
      state: opts.state,
      target_date: opts.targetDate,
      team: opts.team,
    },
  });
}

export type CreateProjectUpdateInput = {
  body: string;
  health?: "onTrack" | "atRisk" | "offTrack";
  project_id: string;
};
export type CreateProjectUpdateOptions = LinearToolOptions & {
  body: Resolvable<string>;
  health?: Resolvable<"onTrack" | "atRisk" | "offTrack" | undefined>;
  projectId: Resolvable<string>;
};
const createProjectUpdateInputSchema: z.ZodType<CreateProjectUpdateInput> =
  z.object({
    body: z.string(),
    health: z.enum(["onTrack", "atRisk", "offTrack"]).optional(),
    project_id: z.string(),
  });
export function createProjectUpdate(
  opts: CreateProjectUpdateOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.CreateProjectUpdate",
    inputSchema: createProjectUpdateInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      body: opts.body,
      health: opts.health,
      project_id: opts.projectId,
    },
  });
}

export type GetCycleInput = {
  cycle_id: string;
};
export type GetCycleOptions = LinearToolOptions & {
  cycleId: Resolvable<string>;
};
const getCycleInputSchema: z.ZodType<GetCycleInput> = z.object({
  cycle_id: z.string(),
});
export function getCycle(
  opts: GetCycleOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetCycle",
    inputSchema: getCycleInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      cycle_id: opts.cycleId,
    },
  });
}

export type GetInitiativeInput = {
  auto_accept_matches?: boolean;
  include_projects?: boolean;
  lookup_by?: "id" | "name";
  value: string;
};
export type GetInitiativeOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  includeProjects?: Resolvable<boolean | undefined>;
  lookupBy?: Resolvable<"id" | "name" | undefined>;
  value: Resolvable<string>;
};
const getInitiativeInputSchema: z.ZodType<GetInitiativeInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  include_projects: z.boolean().optional(),
  lookup_by: z.enum(["id", "name"]).optional(),
  value: z.string(),
});
export function getInitiative(
  opts: GetInitiativeOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetInitiative",
    inputSchema: getInitiativeInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      include_projects: opts.includeProjects,
      lookup_by: opts.lookupBy,
      value: opts.value,
    },
  });
}

export type GetInitiativeDescriptionInput = {
  initiative_id: string;
  limit?: number;
  offset?: number;
};
export type GetInitiativeDescriptionOptions = LinearToolOptions & {
  initiativeId: Resolvable<string>;
  limit?: Resolvable<number | undefined>;
  offset?: Resolvable<number | undefined>;
};
const getInitiativeDescriptionInputSchema: z.ZodType<GetInitiativeDescriptionInput> =
  z.object({
    initiative_id: z.string(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional(),
  });
export function getInitiativeDescription(
  opts: GetInitiativeDescriptionOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetInitiativeDescription",
    inputSchema: getInitiativeDescriptionInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      initiative_id: opts.initiativeId,
      limit: opts.limit,
      offset: opts.offset,
    },
  });
}

export type GetIssueInput = {
  include_attachments?: boolean;
  include_children?: boolean;
  include_comments?: boolean;
  include_relations?: boolean;
  issue_id: string;
};
export type GetIssueOptions = LinearToolOptions & {
  includeAttachments?: Resolvable<boolean | undefined>;
  includeChildren?: Resolvable<boolean | undefined>;
  includeComments?: Resolvable<boolean | undefined>;
  includeRelations?: Resolvable<boolean | undefined>;
  issueId: Resolvable<string>;
};
const getIssueInputSchema: z.ZodType<GetIssueInput> = z.object({
  include_attachments: z.boolean().optional(),
  include_children: z.boolean().optional(),
  include_comments: z.boolean().optional(),
  include_relations: z.boolean().optional(),
  issue_id: z.string(),
});
export function getIssue(
  opts: GetIssueOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetIssue",
    inputSchema: getIssueInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      include_attachments: opts.includeAttachments,
      include_children: opts.includeChildren,
      include_comments: opts.includeComments,
      include_relations: opts.includeRelations,
      issue_id: opts.issueId,
    },
  });
}

export type GetMilestoneInput = {
  auto_accept_matches?: boolean;
  project: string;
  query: string;
};
export type GetMilestoneOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  project: Resolvable<string>;
  query: Resolvable<string>;
};
const getMilestoneInputSchema: z.ZodType<GetMilestoneInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  project: z.string(),
  query: z.string(),
});
export function getMilestone(
  opts: GetMilestoneOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetMilestone",
    inputSchema: getMilestoneInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      project: opts.project,
      query: opts.query,
    },
  });
}

export type GetNotificationsInput = {
  end_cursor?: string;
  limit?: number;
  unread_only?: boolean;
};
export type GetNotificationsOptions = LinearToolOptions & {
  endCursor?: Resolvable<string | undefined>;
  limit?: Resolvable<number | undefined>;
  unreadOnly?: Resolvable<boolean | undefined>;
};
const getNotificationsInputSchema: z.ZodType<GetNotificationsInput> = z.object({
  end_cursor: z.string().optional(),
  limit: z.number().int().optional(),
  unread_only: z.boolean().optional(),
});
export function getNotifications(
  opts: GetNotificationsOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetNotifications",
    inputSchema: getNotificationsInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      end_cursor: opts.endCursor,
      limit: opts.limit,
      unread_only: opts.unreadOnly,
    },
  });
}

export type GetProjectInput = {
  auto_accept_matches?: boolean;
  include_comments?: boolean;
  include_issues?: boolean;
  lookup_by?: "id" | "slug_id" | "name";
  value: string;
};
export type GetProjectOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  includeComments?: Resolvable<boolean | undefined>;
  includeIssues?: Resolvable<boolean | undefined>;
  lookupBy?: Resolvable<"id" | "slug_id" | "name" | undefined>;
  value: Resolvable<string>;
};
const getProjectInputSchema: z.ZodType<GetProjectInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  include_comments: z.boolean().optional(),
  include_issues: z.boolean().optional(),
  lookup_by: z.enum(["id", "slug_id", "name"]).optional(),
  value: z.string(),
});
export function getProject(
  opts: GetProjectOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetProject",
    inputSchema: getProjectInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      include_comments: opts.includeComments,
      include_issues: opts.includeIssues,
      lookup_by: opts.lookupBy,
      value: opts.value,
    },
  });
}

export type GetProjectDescriptionInput = {
  limit?: number;
  offset?: number;
  project_id: string;
};
export type GetProjectDescriptionOptions = LinearToolOptions & {
  limit?: Resolvable<number | undefined>;
  offset?: Resolvable<number | undefined>;
  projectId: Resolvable<string>;
};
const getProjectDescriptionInputSchema: z.ZodType<GetProjectDescriptionInput> =
  z.object({
    limit: z.number().int().optional(),
    offset: z.number().int().optional(),
    project_id: z.string(),
  });
export function getProjectDescription(
  opts: GetProjectDescriptionOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetProjectDescription",
    inputSchema: getProjectDescriptionInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      limit: opts.limit,
      offset: opts.offset,
      project_id: opts.projectId,
    },
  });
}

export type GetRecentActivityInput = {
  days?: number;
  limit?: number;
};
export type GetRecentActivityOptions = LinearToolOptions & {
  days?: Resolvable<number | undefined>;
  limit?: Resolvable<number | undefined>;
};
const getRecentActivityInputSchema: z.ZodType<GetRecentActivityInput> =
  z.object({
    days: z.number().int().optional(),
    limit: z.number().int().optional(),
  });
export function getRecentActivity(
  opts: GetRecentActivityOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetRecentActivity",
    inputSchema: getRecentActivityInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      days: opts.days,
      limit: opts.limit,
    },
  });
}

export type GetTeamInput = {
  auto_accept_matches?: boolean;
  lookup_by?: "id" | "key" | "name";
  value: string;
};
export type GetTeamOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  lookupBy?: Resolvable<"id" | "key" | "name" | undefined>;
  value: Resolvable<string>;
};
const getTeamInputSchema: z.ZodType<GetTeamInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  lookup_by: z.enum(["id", "key", "name"]).optional(),
  value: z.string(),
});
export function getTeam(
  opts: GetTeamOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.GetTeam",
    inputSchema: getTeamInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      lookup_by: opts.lookupBy,
      value: opts.value,
    },
  });
}

export type LinkGithubToIssueInput = {
  github_url: string;
  issue: string;
  title?: string;
};
export type LinkGithubToIssueOptions = LinearToolOptions & {
  githubUrl: Resolvable<string>;
  issue: Resolvable<string>;
  title?: Resolvable<string | undefined>;
};
const linkGithubToIssueInputSchema: z.ZodType<LinkGithubToIssueInput> =
  z.object({
    github_url: z.string(),
    issue: z.string(),
    title: z.string().optional(),
  });
export function linkGithubToIssue(
  opts: LinkGithubToIssueOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.LinkGithubToIssue",
    inputSchema: linkGithubToIssueInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      github_url: opts.githubUrl,
      issue: opts.issue,
      title: opts.title,
    },
  });
}

export type ListCommentsInput = {
  end_cursor?: string;
  issue: string;
  limit?: number;
};
export type ListCommentsOptions = LinearToolOptions & {
  endCursor?: Resolvable<string | undefined>;
  issue: Resolvable<string>;
  limit?: Resolvable<number | undefined>;
};
const listCommentsInputSchema: z.ZodType<ListCommentsInput> = z.object({
  end_cursor: z.string().optional(),
  issue: z.string(),
  limit: z.number().int().optional(),
});
export function listComments(
  opts: ListCommentsOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListComments",
    inputSchema: listCommentsInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      end_cursor: opts.endCursor,
      issue: opts.issue,
      limit: opts.limit,
    },
  });
}

export type ListCyclesInput = {
  active_only?: boolean;
  end_cursor?: string;
  include_completed?: boolean;
  limit?: number;
  team?: string;
};
export type ListCyclesOptions = LinearToolOptions & {
  activeOnly?: Resolvable<boolean | undefined>;
  endCursor?: Resolvable<string | undefined>;
  includeCompleted?: Resolvable<boolean | undefined>;
  limit?: Resolvable<number | undefined>;
  team?: Resolvable<string | undefined>;
};
const listCyclesInputSchema: z.ZodType<ListCyclesInput> = z.object({
  active_only: z.boolean().optional(),
  end_cursor: z.string().optional(),
  include_completed: z.boolean().optional(),
  limit: z.number().int().optional(),
  team: z.string().optional(),
});
export function listCycles(
  opts: ListCyclesOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListCycles",
    inputSchema: listCyclesInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      active_only: opts.activeOnly,
      end_cursor: opts.endCursor,
      include_completed: opts.includeCompleted,
      limit: opts.limit,
      team: opts.team,
    },
  });
}

export type ListInitiativesInput = {
  end_cursor?: string;
  keywords?: string;
  limit?: number;
  state?:
    | "Backlog"
    | "Planned"
    | "Active"
    | "Paused"
    | "Completed"
    | "Canceled";
};
export type ListInitiativesOptions = LinearToolOptions & {
  endCursor?: Resolvable<string | undefined>;
  keywords?: Resolvable<string | undefined>;
  limit?: Resolvable<number | undefined>;
  state?: Resolvable<
    | "Backlog"
    | "Planned"
    | "Active"
    | "Paused"
    | "Completed"
    | "Canceled"
    | undefined
  >;
};
const listInitiativesInputSchema: z.ZodType<ListInitiativesInput> = z.object({
  end_cursor: z.string().optional(),
  keywords: z.string().optional(),
  limit: z.number().int().optional(),
  state: z
    .enum(["Backlog", "Planned", "Active", "Paused", "Completed", "Canceled"])
    .optional(),
});
export function listInitiatives(
  opts: ListInitiativesOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListInitiatives",
    inputSchema: listInitiativesInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      end_cursor: opts.endCursor,
      keywords: opts.keywords,
      limit: opts.limit,
      state: opts.state,
    },
  });
}

export type ListIssuesInput = {
  assignee?: string;
  created_after?: string;
  end_cursor?: string;
  keywords?: string;
  label?: string;
  limit?: number;
  priority?: "none" | "urgent" | "high" | "medium" | "low";
  project?: string;
  state?: string;
  team?: string;
};
export type ListIssuesOptions = LinearToolOptions & {
  assignee?: Resolvable<string | undefined>;
  createdAfter?: Resolvable<string | undefined>;
  endCursor?: Resolvable<string | undefined>;
  keywords?: Resolvable<string | undefined>;
  label?: Resolvable<string | undefined>;
  limit?: Resolvable<number | undefined>;
  priority?: Resolvable<
    "none" | "urgent" | "high" | "medium" | "low" | undefined
  >;
  project?: Resolvable<string | undefined>;
  state?: Resolvable<string | undefined>;
  team?: Resolvable<string | undefined>;
};
const listIssuesInputSchema: z.ZodType<ListIssuesInput> = z.object({
  assignee: z.string().optional(),
  created_after: z.string().optional(),
  end_cursor: z.string().optional(),
  keywords: z.string().optional(),
  label: z.string().optional(),
  limit: z.number().int().optional(),
  priority: z.enum(["none", "urgent", "high", "medium", "low"]).optional(),
  project: z.string().optional(),
  state: z.string().optional(),
  team: z.string().optional(),
});
export function listIssues(
  opts: ListIssuesOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListIssues",
    inputSchema: listIssuesInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      assignee: opts.assignee,
      created_after: opts.createdAfter,
      end_cursor: opts.endCursor,
      keywords: opts.keywords,
      label: opts.label,
      limit: opts.limit,
      priority: opts.priority,
      project: opts.project,
      state: opts.state,
      team: opts.team,
    },
  });
}

export type ListLabelsInput = {
  limit?: number;
};
export type ListLabelsOptions = LinearToolOptions & {
  limit?: Resolvable<number | undefined>;
};
const listLabelsInputSchema: z.ZodType<ListLabelsInput> = z.object({
  limit: z.number().int().optional(),
});
export function listLabels(
  opts: ListLabelsOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListLabels",
    inputSchema: listLabelsInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      limit: opts.limit,
    },
  });
}

export type ListMilestonesInput = {
  auto_accept_matches?: boolean;
  end_cursor?: string;
  limit?: number;
  project: string;
};
export type ListMilestonesOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  endCursor?: Resolvable<string | undefined>;
  limit?: Resolvable<number | undefined>;
  project: Resolvable<string>;
};
const listMilestonesInputSchema: z.ZodType<ListMilestonesInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  end_cursor: z.string().optional(),
  limit: z.number().int().optional(),
  project: z.string(),
});
export function listMilestones(
  opts: ListMilestonesOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListMilestones",
    inputSchema: listMilestonesInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      end_cursor: opts.endCursor,
      limit: opts.limit,
      project: opts.project,
    },
  });
}

export type ListProjectCommentsInput = {
  auto_accept_matches?: boolean;
  comment_filter?: "only_quoted" | "only_unquoted" | "all";
  end_cursor?: string;
  include_resolved?: boolean;
  limit?: number;
  project: string;
};
export type ListProjectCommentsOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  commentFilter?: Resolvable<
    "only_quoted" | "only_unquoted" | "all" | undefined
  >;
  endCursor?: Resolvable<string | undefined>;
  includeResolved?: Resolvable<boolean | undefined>;
  limit?: Resolvable<number | undefined>;
  project: Resolvable<string>;
};
const listProjectCommentsInputSchema: z.ZodType<ListProjectCommentsInput> =
  z.object({
    auto_accept_matches: z.boolean().optional(),
    comment_filter: z.enum(["only_quoted", "only_unquoted", "all"]).optional(),
    end_cursor: z.string().optional(),
    include_resolved: z.boolean().optional(),
    limit: z.number().int().optional(),
    project: z.string(),
  });
export function listProjectComments(
  opts: ListProjectCommentsOptions,
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListProjectComments",
    inputSchema: listProjectCommentsInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      comment_filter: opts.commentFilter,
      end_cursor: opts.endCursor,
      include_resolved: opts.includeResolved,
      limit: opts.limit,
      project: opts.project,
    },
  });
}

export type ListProjectsInput = {
  created_after?: string;
  end_cursor?: string;
  keywords?: string;
  limit?: number;
  state?: string;
  team?: string;
};
export type ListProjectsOptions = LinearToolOptions & {
  createdAfter?: Resolvable<string | undefined>;
  endCursor?: Resolvable<string | undefined>;
  keywords?: Resolvable<string | undefined>;
  limit?: Resolvable<number | undefined>;
  state?: Resolvable<string | undefined>;
  team?: Resolvable<string | undefined>;
};
const listProjectsInputSchema: z.ZodType<ListProjectsInput> = z.object({
  created_after: z.string().optional(),
  end_cursor: z.string().optional(),
  keywords: z.string().optional(),
  limit: z.number().int().optional(),
  state: z.string().optional(),
  team: z.string().optional(),
});
export function listProjects(
  opts: ListProjectsOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListProjects",
    inputSchema: listProjectsInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      created_after: opts.createdAfter,
      end_cursor: opts.endCursor,
      keywords: opts.keywords,
      limit: opts.limit,
      state: opts.state,
      team: opts.team,
    },
  });
}

export type ListTeamsInput = {
  created_after?: string;
  end_cursor?: string;
  include_archived?: boolean;
  keywords?: string;
  limit?: number;
};
export type ListTeamsOptions = LinearToolOptions & {
  createdAfter?: Resolvable<string | undefined>;
  endCursor?: Resolvable<string | undefined>;
  includeArchived?: Resolvable<boolean | undefined>;
  keywords?: Resolvable<string | undefined>;
  limit?: Resolvable<number | undefined>;
};
const listTeamsInputSchema: z.ZodType<ListTeamsInput> = z.object({
  created_after: z.string().optional(),
  end_cursor: z.string().optional(),
  include_archived: z.boolean().optional(),
  keywords: z.string().optional(),
  limit: z.number().int().optional(),
});
export function listTeams(
  opts: ListTeamsOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListTeams",
    inputSchema: listTeamsInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      created_after: opts.createdAfter,
      end_cursor: opts.endCursor,
      include_archived: opts.includeArchived,
      keywords: opts.keywords,
      limit: opts.limit,
    },
  });
}

export type ListWorkflowStatesInput = {
  limit?: number;
  state_type?:
    | "triage"
    | "backlog"
    | "unstarted"
    | "started"
    | "completed"
    | "canceled";
  team?: string;
};
export type ListWorkflowStatesOptions = LinearToolOptions & {
  limit?: Resolvable<number | undefined>;
  stateType?: Resolvable<
    | "triage"
    | "backlog"
    | "unstarted"
    | "started"
    | "completed"
    | "canceled"
    | undefined
  >;
  team?: Resolvable<string | undefined>;
};
const listWorkflowStatesInputSchema: z.ZodType<ListWorkflowStatesInput> =
  z.object({
    limit: z.number().int().optional(),
    state_type: z
      .enum([
        "triage",
        "backlog",
        "unstarted",
        "started",
        "completed",
        "canceled",
      ])
      .optional(),
    team: z.string().optional(),
  });
export function listWorkflowStates(
  opts: ListWorkflowStatesOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.ListWorkflowStates",
    inputSchema: listWorkflowStatesInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      limit: opts.limit,
      state_type: opts.stateType,
      team: opts.team,
    },
  });
}

export type ManageIssueSubscriptionInput = {
  issue: string;
  subscribe: boolean;
};
export type ManageIssueSubscriptionOptions = LinearToolOptions & {
  issue: Resolvable<string>;
  subscribe: Resolvable<boolean>;
};
const manageIssueSubscriptionInputSchema: z.ZodType<ManageIssueSubscriptionInput> =
  z.object({
    issue: z.string(),
    subscribe: z.boolean(),
  });
export function manageIssueSubscription(
  opts: ManageIssueSubscriptionOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.ManageIssueSubscription",
    inputSchema: manageIssueSubscriptionInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      issue: opts.issue,
      subscribe: opts.subscribe,
    },
  });
}

export type ReplyToCommentInput = {
  body: string;
  issue: string;
  parent_comment_id: string;
};
export type ReplyToCommentOptions = LinearToolOptions & {
  body: Resolvable<string>;
  issue: Resolvable<string>;
  parentCommentId: Resolvable<string>;
};
const replyToCommentInputSchema: z.ZodType<ReplyToCommentInput> = z.object({
  body: z.string(),
  issue: z.string(),
  parent_comment_id: z.string(),
});
export function replyToComment(
  opts: ReplyToCommentOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.ReplyToComment",
    inputSchema: replyToCommentInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      body: opts.body,
      issue: opts.issue,
      parent_comment_id: opts.parentCommentId,
    },
  });
}

export type ReplyToProjectCommentInput = {
  auto_accept_matches?: boolean;
  body: string;
  parent_comment_id: string;
  project: string;
};
export type ReplyToProjectCommentOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  body: Resolvable<string>;
  parentCommentId: Resolvable<string>;
  project: Resolvable<string>;
};
const replyToProjectCommentInputSchema: z.ZodType<ReplyToProjectCommentInput> =
  z.object({
    auto_accept_matches: z.boolean().optional(),
    body: z.string(),
    parent_comment_id: z.string(),
    project: z.string(),
  });
export function replyToProjectComment(
  opts: ReplyToProjectCommentOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.ReplyToProjectComment",
    inputSchema: replyToProjectCommentInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      body: opts.body,
      parent_comment_id: opts.parentCommentId,
      project: opts.project,
    },
  });
}

export type TransitionIssueStateInput = {
  auto_accept_matches?: boolean;
  issue_id: string;
  target_state: string;
};
export type TransitionIssueStateOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  issueId: Resolvable<string>;
  targetState: Resolvable<string>;
};
const transitionIssueStateInputSchema: z.ZodType<TransitionIssueStateInput> =
  z.object({
    auto_accept_matches: z.boolean().optional(),
    issue_id: z.string(),
    target_state: z.string(),
  });
export function transitionIssueState(
  opts: TransitionIssueStateOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.TransitionIssueState",
    inputSchema: transitionIssueStateInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      issue_id: opts.issueId,
      target_state: opts.targetState,
    },
  });
}

export type UpdateCommentInput = {
  body: string;
  comment_id: string;
};
export type UpdateCommentOptions = LinearToolOptions & {
  body: Resolvable<string>;
  commentId: Resolvable<string>;
};
const updateCommentInputSchema: z.ZodType<UpdateCommentInput> = z.object({
  body: z.string(),
  comment_id: z.string(),
});
export function updateComment(
  opts: UpdateCommentOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.UpdateComment",
    inputSchema: updateCommentInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      body: opts.body,
      comment_id: opts.commentId,
    },
  });
}

export type UpdateInitiativeInput = {
  description?: string;
  initiative_id: string;
  name?: string;
  status?:
    | "Backlog"
    | "Planned"
    | "Active"
    | "Paused"
    | "Completed"
    | "Canceled";
  target_date?: string;
};
export type UpdateInitiativeOptions = LinearToolOptions & {
  description?: Resolvable<string | undefined>;
  initiativeId: Resolvable<string>;
  name?: Resolvable<string | undefined>;
  status?: Resolvable<
    | "Backlog"
    | "Planned"
    | "Active"
    | "Paused"
    | "Completed"
    | "Canceled"
    | undefined
  >;
  targetDate?: Resolvable<string | undefined>;
};
const updateInitiativeInputSchema: z.ZodType<UpdateInitiativeInput> = z.object({
  description: z.string().optional(),
  initiative_id: z.string(),
  name: z.string().optional(),
  status: z
    .enum(["Backlog", "Planned", "Active", "Paused", "Completed", "Canceled"])
    .optional(),
  target_date: z.string().optional(),
});
export function updateInitiative(
  opts: UpdateInitiativeOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.UpdateInitiative",
    inputSchema: updateInitiativeInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      description: opts.description,
      initiative_id: opts.initiativeId,
      name: opts.name,
      status: opts.status,
      target_date: opts.targetDate,
    },
  });
}

export type UpdateIssueInput = {
  assignee?: string;
  attachment_title?: string;
  attachment_url?: string;
  auto_accept_matches?: boolean;
  cycle?: string;
  description?: string;
  due_date?: string;
  estimate?: number;
  issue_id: string;
  labels_to_add?: string[];
  labels_to_remove?: string[];
  priority?: "none" | "urgent" | "high" | "medium" | "low";
  project?: string;
  state?: string;
  title?: string;
};
export type UpdateIssueOptions = LinearToolOptions & {
  assignee?: Resolvable<string | undefined>;
  attachmentTitle?: Resolvable<string | undefined>;
  attachmentUrl?: Resolvable<string | undefined>;
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  cycle?: Resolvable<string | undefined>;
  description?: Resolvable<string | undefined>;
  dueDate?: Resolvable<string | undefined>;
  estimate?: Resolvable<number | undefined>;
  issueId: Resolvable<string>;
  labelsToAdd?: Resolvable<string[] | undefined>;
  labelsToRemove?: Resolvable<string[] | undefined>;
  priority?: Resolvable<
    "none" | "urgent" | "high" | "medium" | "low" | undefined
  >;
  project?: Resolvable<string | undefined>;
  state?: Resolvable<string | undefined>;
  title?: Resolvable<string | undefined>;
};
const updateIssueInputSchema: z.ZodType<UpdateIssueInput> = z.object({
  assignee: z.string().optional(),
  attachment_title: z.string().optional(),
  attachment_url: z.string().optional(),
  auto_accept_matches: z.boolean().optional(),
  cycle: z.string().optional(),
  description: z.string().optional(),
  due_date: z.string().optional(),
  estimate: z.number().int().optional(),
  issue_id: z.string(),
  labels_to_add: z.array(z.string()).optional(),
  labels_to_remove: z.array(z.string()).optional(),
  priority: z.enum(["none", "urgent", "high", "medium", "low"]).optional(),
  project: z.string().optional(),
  state: z.string().optional(),
  title: z.string().optional(),
});
export function updateIssue(
  opts: UpdateIssueOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.UpdateIssue",
    inputSchema: updateIssueInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      assignee: opts.assignee,
      attachment_title: opts.attachmentTitle,
      attachment_url: opts.attachmentUrl,
      auto_accept_matches: opts.autoAcceptMatches,
      cycle: opts.cycle,
      description: opts.description,
      due_date: opts.dueDate,
      estimate: opts.estimate,
      issue_id: opts.issueId,
      labels_to_add: opts.labelsToAdd,
      labels_to_remove: opts.labelsToRemove,
      priority: opts.priority,
      project: opts.project,
      state: opts.state,
      title: opts.title,
    },
  });
}

export type UpdateProjectInput = {
  auto_accept_matches?: boolean;
  content?: string;
  description?: string;
  lead?: string;
  name?: string;
  project_id: string;
  start_date?: string;
  state?:
    | "backlog"
    | "planned"
    | "started"
    | "paused"
    | "completed"
    | "canceled";
  target_date?: string;
  teams_to_add?: string[];
  teams_to_remove?: string[];
};
export type UpdateProjectOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  content?: Resolvable<string | undefined>;
  description?: Resolvable<string | undefined>;
  lead?: Resolvable<string | undefined>;
  name?: Resolvable<string | undefined>;
  projectId: Resolvable<string>;
  startDate?: Resolvable<string | undefined>;
  state?: Resolvable<
    | "backlog"
    | "planned"
    | "started"
    | "paused"
    | "completed"
    | "canceled"
    | undefined
  >;
  targetDate?: Resolvable<string | undefined>;
  teamsToAdd?: Resolvable<string[] | undefined>;
  teamsToRemove?: Resolvable<string[] | undefined>;
};
const updateProjectInputSchema: z.ZodType<UpdateProjectInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  content: z.string().optional(),
  description: z.string().optional(),
  lead: z.string().optional(),
  name: z.string().optional(),
  project_id: z.string(),
  start_date: z.string().optional(),
  state: z
    .enum(["backlog", "planned", "started", "paused", "completed", "canceled"])
    .optional(),
  target_date: z.string().optional(),
  teams_to_add: z.array(z.string()).optional(),
  teams_to_remove: z.array(z.string()).optional(),
});
export function updateProject(
  opts: UpdateProjectOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.UpdateProject",
    inputSchema: updateProjectInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      content: opts.content,
      description: opts.description,
      lead: opts.lead,
      name: opts.name,
      project_id: opts.projectId,
      start_date: opts.startDate,
      state: opts.state,
      target_date: opts.targetDate,
      teams_to_add: opts.teamsToAdd,
      teams_to_remove: opts.teamsToRemove,
    },
  });
}

export type UpsertMilestoneInput = {
  auto_accept_matches?: boolean;
  description?: string;
  milestone_id?: string;
  name?: string;
  project: string;
  target_date?: string;
};
export type UpsertMilestoneOptions = LinearToolOptions & {
  autoAcceptMatches?: Resolvable<boolean | undefined>;
  description?: Resolvable<string | undefined>;
  milestoneId?: Resolvable<string | undefined>;
  name?: Resolvable<string | undefined>;
  project: Resolvable<string>;
  targetDate?: Resolvable<string | undefined>;
};
const upsertMilestoneInputSchema: z.ZodType<UpsertMilestoneInput> = z.object({
  auto_accept_matches: z.boolean().optional(),
  description: z.string().optional(),
  milestone_id: z.string().optional(),
  name: z.string().optional(),
  project: z.string(),
  target_date: z.string().optional(),
});
export function upsertMilestone(
  opts: UpsertMilestoneOptions,
): LinearToolAction<Record<string, unknown>> {
  return toolkitTool({
    toolName: "Linear.UpsertMilestone",
    inputSchema: upsertMilestoneInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {
      auto_accept_matches: opts.autoAcceptMatches,
      description: opts.description,
      milestone_id: opts.milestoneId,
      name: opts.name,
      project: opts.project,
      target_date: opts.targetDate,
    },
  });
}

export type WhoAmIInput = Record<string, never>;
export type WhoAmIOptions = LinearToolOptions;
const emptyInputSchema = z.object({});
export function whoAmI(
  opts: WhoAmIOptions = {},
): LinearToolAtom<Record<string, unknown>> {
  return toolkitAtomTool({
    toolName: "Linear.WhoAmI",
    inputSchema: emptyInputSchema,
    outputSchema: jsonObjectSchema,
    opts,
    input: {},
  });
}

function toolkitTool<Input extends Record<string, unknown>, Value>(args: {
  toolName: string;
  inputSchema: z.ZodType<Input>;
  outputSchema: z.ZodType<Value>;
  opts: LinearToolOptions;
  input: { [K in keyof Input]: MaybeHandle<Input[K]> | undefined };
}): Action<ArcadeToolResult<Value>> {
  return createArcadeToolAction({
    ...args,
    defaultToolVersion: LINEAR_TOOL_VERSION,
  });
}

function toolkitAtomTool<Input extends Record<string, unknown>, Value>(args: {
  toolName: string;
  inputSchema: z.ZodType<Input>;
  outputSchema: z.ZodType<Value>;
  opts: LinearToolOptions;
  input: { [K in keyof Input]: MaybeHandle<Input[K]> | undefined };
}): Atom<ArcadeToolResult<Value>> {
  return createArcadeToolAtom({
    ...args,
    defaultToolVersion: LINEAR_TOOL_VERSION,
  });
}
