import { spawn } from "node:child_process";
import {
  access,
  cp,
  mkdir,
  readdir,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { relative, resolve } from "node:path";
import { flamecastRoot } from "../flamecast-root.js";
import { info } from "../log.js";
import { scaffoldDir } from "../paths.js";

const DEFAULT_EXAMPLE_WORKER_NAME = "workflow-cloudflare-worker-example";
const ROOT_GITIGNORE = [".logs", ".raw", ".sessions/", "flamecast.log"].join(
  "\n",
);
const ROOT_DIRECTORIES = [".logs", ".raw", ".sessions"];
const EMPTY_STATE_APP_PORT = 3457;
const EMPTY_STATE_APP_PRESET = "b5AxX80P68";
const EMPTY_STATE_APP_PORTLESS_ALIAS = "empty-state-app";

const HYLO_START_WRAPPER = `// Auto-generated by "hylo init". Boots the embedded app's Vite dev server
// with a forced port/host so portless can proxy to it. Loads the project's
// own vite.config.ts (plugins, routing, etc.) and only overrides server bind.
import { createServer } from "vite";

const port = Number(process.env.HYLO_EMPTY_STATE_APP_PORT) || ${EMPTY_STATE_APP_PORT};

const server = await createServer({
  server: {
    port,
    host: "127.0.0.1",
    strictPort: true,
    allowedHosts: true,
  },
});

await server.listen();
server.printUrls();

const shutdown = () => {
  server.close().finally(() => process.exit(0));
};
process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);
`;
const WORKSPACE_DEPENDENCY_PATHS: Record<string, string> = {
  "@hylo/cli": "packages/cli",
  "@workflow/core": "packages/core",
  "@workflow/integrations-gmail": "packages/integrations/gmail",
  "@workflow/integrations-linear": "packages/integrations/linear",
  "@workflow/integrations-oauth": "packages/integrations/_oauth",
  "@workflow/runtime": "packages/runtime",
  "@workflow/server": "packages/server",
};

export async function runInit(args: string[]): Promise<number> {
  if (args.includes("--help") || args.includes("-h")) {
    process.stdout.write(
      [
        "Usage: hylo init [--force] [--no-empty-state-app]",
        "",
        "Creates ~/.flamecast with an example Hylo Worker at ~/.flamecast/worker.",
        "On first run, also scaffolds a TanStack Start app at",
        "~/.flamecast/empty-state-app (rendered in the chat empty state).",
        "",
        "Without --force, existing ~/.flamecast/worker and",
        "~/.flamecast/empty-state-app directories are left alone.",
        "",
        "Options:",
        "  --force                Wipe ~/.flamecast entirely and re-scaffold",
        "                         from scratch (worker + empty-state-app)",
        "  --no-empty-state-app   Skip scaffolding the TanStack Start app",
        "",
      ].join("\n"),
    );
    return 0;
  }

  const force = args.includes("--force");
  const skipEmptyStateApp = args.includes("--no-empty-state-app");
  const unexpectedArgs = args.filter(
    (arg) => arg !== "--force" && arg !== "--no-empty-state-app",
  );
  if (unexpectedArgs.length > 0) {
    process.stderr.write(
      "hylo init only accepts --force and --no-empty-state-app.\n",
    );
    return 1;
  }

  const root = flamecastRoot();

  if (force) {
    info(`Wiping ${root}…`);
    await rm(root, { force: true, recursive: true });
  }

  const target = resolve(root, "worker");
  const emptyStateAppTarget = resolve(root, "empty-state-app");
  const manifestPath = resolve(emptyStateAppTarget, "manifest.json");

  await ensureRoot(root);

  const workerExists = await access(target)
    .then(() => true)
    .catch(() => false);
  if (workerExists) {
    info(`Hylo example worker already exists at ${target}, leaving it alone.`);
  } else {
    await cp(scaffoldDir, target, {
      force: false,
      recursive: true,
    });
    const targetPackageJson = resolve(target, "package.json");
    await writeFile(
      targetPackageJson,
      await renderPackageJson(target, targetPackageJson),
    );
    info(`Initialized Hylo example worker at ${target}`);
    info(`Run it locally with: hylo dev ~/.flamecast/worker`);
  }

  if (!skipEmptyStateApp) {
    const manifestExists = await access(manifestPath)
      .then(() => true)
      .catch(() => false);
    if (manifestExists) {
      info(
        `Empty-state app already initialized at ${emptyStateAppTarget}, leaving it alone.`,
      );
    } else {
      await rm(emptyStateAppTarget, { force: true, recursive: true });
      await scaffoldEmptyStateApp(emptyStateAppTarget);
    }
  }

  return 0;
}

async function scaffoldEmptyStateApp(target: string): Promise<void> {
  await mkdir(target, { recursive: true });

  info(`Scaffolding TanStack Start app at ${target}…`);
  const shadcnCode = await runShadcnInit(target);
  await dumpDirListing(target);
  if (shadcnCode !== 0) {
    process.stderr.write(
      `Warning: shadcn init exited with code ${shadcnCode}. Skipping empty-state app — leaving ${target} in place for inspection. Delete it and re-run "hylo init" to retry.\n`,
    );
    return;
  }

  const projectDir = await findScaffoldedProjectDir(target);
  if (!projectDir) {
    process.stderr.write(
      `Warning: shadcn didn't produce a package.json under ${target}. Leaving directory in place — please paste its contents (see listing above) so we can adjust hylo init.\n`,
    );
    return;
  }
  info(`Detected scaffolded project at ${projectDir}`);

  const nodeModulesExists = await access(resolve(projectDir, "node_modules"))
    .then(() => true)
    .catch(() => false);
  if (nodeModulesExists) {
    info(
      `node_modules already present in ${projectDir} (shadcn ran the install), skipping our npm install.`,
    );
  } else {
    info(`Installing dependencies in ${projectDir}…`);
    const installCode = await runNpmInstall(projectDir);
    if (installCode !== 0) {
      process.stderr.write(
        `Warning: npm install exited with code ${installCode}. Empty-state app left in place but unbuilt — run "npm install" in ${projectDir} manually.\n`,
      );
      return;
    }
  }

  const wrapperPath = resolve(projectDir, "__hylo-start.mjs");
  await writeFile(wrapperPath, HYLO_START_WRAPPER);

  const manifestPath = resolve(target, "manifest.json");
  const manifestCwd = relative(target, projectDir);
  const manifest = {
    command: "node",
    args: ["__hylo-start.mjs"],
    ...(manifestCwd ? { cwd: manifestCwd } : {}),
    port: EMPTY_STATE_APP_PORT,
    url: `https://${EMPTY_STATE_APP_PORTLESS_ALIAS}.localhost`,
  };
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  info(`Initialized empty-state app at ${target}`);
  info(`It will auto-start with local-api on port ${EMPTY_STATE_APP_PORT}.`);
}

async function dumpDirListing(dir: string, depth = 2): Promise<void> {
  info(`Listing ${dir} (depth=${depth}):`);
  const lines = await listRecursive(dir, depth, "");
  if (lines.length === 0) {
    info(`  (empty)`);
    return;
  }
  for (const line of lines) info(`  ${line}`);
}

async function listRecursive(
  dir: string,
  depth: number,
  indent: string,
): Promise<string[]> {
  let entries: import("node:fs").Dirent[];
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return [`${indent}<missing: ${dir}>`];
  }
  entries.sort((a, b) => a.name.localeCompare(b.name));
  const out: string[] = [];
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".git") {
      out.push(`${indent}${entry.name}/ (skipped)`);
      continue;
    }
    if (entry.isDirectory()) {
      out.push(`${indent}${entry.name}/`);
      if (depth > 0) {
        out.push(
          ...(await listRecursive(
            resolve(dir, entry.name),
            depth - 1,
            `${indent}  `,
          )),
        );
      }
    } else {
      out.push(`${indent}${entry.name}`);
    }
  }
  return out;
}

async function findScaffoldedProjectDir(
  target: string,
): Promise<string | null> {
  const topLevel = resolve(target, "package.json");
  if (
    await access(topLevel)
      .then(() => true)
      .catch(() => false)
  ) {
    return target;
  }
  const subdir = resolve(target, "frontend");
  if (
    await access(resolve(subdir, "package.json"))
      .then(() => true)
      .catch(() => false)
  ) {
    info(`shadcn scaffolded into subdirectory: ${subdir}`);
    return subdir;
  }
  return null;
}

function runNpmInstall(cwd: string): Promise<number> {
  return new Promise((resolveExit) => {
    const child = spawn("npm", ["install"], { cwd, stdio: "inherit" });
    child.on("error", (err) => {
      process.stderr.write(`Failed to launch npm: ${err.message}\n`);
      resolveExit(1);
    });
    child.on("exit", (code, signal) => {
      resolveExit(signal ? 1 : (code ?? 1));
    });
  });
}

function runShadcnInit(cwd: string): Promise<number> {
  return new Promise((resolveExit) => {
    const child = spawn(
      "npx",
      [
        "--yes",
        "shadcn@latest",
        "init",
        "--yes",
        "--preset",
        EMPTY_STATE_APP_PRESET,
        "--template",
        "start",
        "--name",
        "frontend",
      ],
      { cwd, stdio: "inherit" },
    );
    child.on("error", (err) => {
      process.stderr.write(`Failed to launch npx: ${err.message}\n`);
      resolveExit(1);
    });
    child.on("exit", (code, signal) => {
      if (signal) {
        resolveExit(1);
      } else {
        resolveExit(code ?? 1);
      }
    });
  });
}

async function ensureRoot(root: string): Promise<void> {
  await mkdir(root, { recursive: true });
  await Promise.all(
    ROOT_DIRECTORIES.map((dir) =>
      mkdir(resolve(root, dir), { recursive: true }),
    ),
  );
  await writeFileIfMissing(resolve(root, ".gitignore"), `${ROOT_GITIGNORE}\n`);
}

async function writeFileIfMissing(
  path: string,
  contents: string,
): Promise<void> {
  await writeFile(path, contents, { flag: "wx" }).catch((err: unknown) => {
    if (
      err &&
      typeof err === "object" &&
      "code" in err &&
      err.code === "EEXIST"
    ) {
      return;
    }
    throw err;
  });
}

async function renderPackageJson(
  target: string,
  packageJsonPath: string,
): Promise<string> {
  const raw = (await readFile(packageJsonPath, "utf8")).replaceAll(
    "{{name}}",
    DEFAULT_EXAMPLE_WORKER_NAME,
  );
  const pkg = JSON.parse(raw) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };

  for (const dependencies of [pkg.dependencies, pkg.devDependencies]) {
    if (!dependencies) continue;
    for (const [name, localPath] of Object.entries(
      WORKSPACE_DEPENDENCY_PATHS,
    )) {
      if (dependencies[name] !== "workspace:*") continue;
      const absoluteLocalPath = resolve(
        scaffoldDir,
        "..",
        "..",
        "..",
        "..",
        localPath,
      );
      const localPackageExists = await access(
        resolve(absoluteLocalPath, "package.json"),
      )
        .then(() => true)
        .catch(() => false);
      if (!localPackageExists) continue;
      dependencies[name] = `link:${relative(target, absoluteLocalPath)}`;
    }
  }

  return `${JSON.stringify(pkg, null, 2)}\n`;
}
