import { spawn } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { createServer } from "node:net";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const devVarsPath = join(appRoot, ".dev.vars");
const prepareOnly = process.argv.includes("--prepare-only");

const managedVars = [
  "HYLO_API_KEY",
  "HYLO_BACKEND_PUBLIC_URL",
  "HYLO_BROKER_BASE_URL",
  "NOTION_CLIENT_ID",
  "NOTION_CLIENT_SECRET",
  "SPOTIFY_CLIENT_ID",
  "SPOTIFY_CLIENT_SECRET",
];

const existing = readExistingDevVars();
const values = new Map(existing);

setDefault("HYLO_API_KEY", "local-dev-hylo-api-key");
setDefault(
  "HYLO_BACKEND_PUBLIC_URL",
  process.env.PORTLESS_URL ?? "https://api-worker.hylo.localhost",
);

for (const key of managedVars) {
  const value = process.env[key]?.trim();
  if (value) values.set(key, value);
}

writeDevVars(values);
printProviderStatus(values);

if (prepareOnly) process.exit(0);

const port = process.env.PORT || "8788";
const inspectorPort =
  process.env.WRANGLER_INSPECTOR_PORT ?? String(await freePort());
const child = spawn(
  "wrangler",
  [
    "dev",
    "--ip",
    "127.0.0.1",
    "--port",
    port,
    "--inspector-ip",
    "127.0.0.1",
    "--inspector-port",
    inspectorPort,
  ],
  {
    cwd: appRoot,
    stdio: "inherit",
    shell: false,
  },
);

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => {
    child.kill(signal);
  });
}

child.on("exit", (code, signal) => {
  if (signal) process.kill(process.pid, signal);
  process.exit(code ?? 0);
});

function setDefault(key, value) {
  if (!values.get(key)?.trim()) values.set(key, value);
}

function readExistingDevVars() {
  try {
    return parseDevVars(readFileSync(devVarsPath, "utf8"));
  } catch (error) {
    if (error && error.code === "ENOENT") return new Map();
    throw error;
  }
}

function parseDevVars(source) {
  const parsed = new Map();
  for (const line of source.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const match = trimmed.match(/^([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (!match) continue;
    parsed.set(match[1], unquote(match[2].trim()));
  }
  return parsed;
}

function unquote(value) {
  if (!value) return "";
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function writeDevVars(vars) {
  const lines = [
    "# Generated by pnpm --filter backend dev.",
    "# Safe to edit locally; this file is gitignored.",
    "",
  ];

  for (const key of managedVars) {
    lines.push(`${key}=${JSON.stringify(vars.get(key) ?? "")}`);
  }

  writeFileSync(devVarsPath, `${lines.join("\n")}\n`);
}

function printProviderStatus(vars) {
  const providers = [
    ["notion", "NOTION_CLIENT_ID", "NOTION_CLIENT_SECRET"],
    ["spotify", "SPOTIFY_CLIENT_ID", "SPOTIFY_CLIENT_SECRET"],
  ];
  const statuses = providers.map(([name, idKey, secretKey]) => {
    const configured = Boolean(vars.get(idKey)?.trim() && vars.get(secretKey));
    return `${name}:${configured ? "configured" : "missing"}`;
  });
  console.log(`[backend] wrote .dev.vars (${statuses.join(", ")})`);
}

function freePort() {
  return new Promise((resolve, reject) => {
    const server = createServer();
    server.on("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      server.close((error) => {
        if (error) {
          reject(error);
          return;
        }
        if (!address || typeof address === "string") {
          reject(new Error("Unable to allocate a Wrangler inspector port."));
          return;
        }
        resolve(address.port);
      });
    });
  });
}
