import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type ValueSchema = {
  val_type: string;
  inner_val_type?: string;
  enum?: string[];
};

type ToolParameter = {
  name: string;
  required?: boolean;
  description?: string;
  value_schema: ValueSchema;
};

type ToolResponse = {
  name: string;
  qualified_name: string;
  fully_qualified_name?: string;
  description?: string;
  input?: { parameters?: ToolParameter[] };
  output?: { value_schema?: ValueSchema };
  metadata?: {
    behavior?: {
      read_only?: boolean;
      destructive?: boolean;
      idempotent?: boolean;
    };
  };
  toolkit?: {
    name: string;
    version?: string;
  };
};

type Snapshot = {
  toolkit: string;
  tools: ToolResponse[];
};

type Options = {
  toolkit: string;
  outDir: string;
  snapshotPath: string;
  apiKey?: string;
  baseUrl: string;
  packageName?: string;
  force: boolean;
  noFetch: boolean;
};

const GENERATED_HEADER =
  "/* Generated by scripts/generate-arcade-integration.ts. Do not edit by hand. */\n";

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  const snapshot = await loadSnapshot(opts);
  const tools = normalizeTools(snapshot.tools);
  if (tools.length === 0) {
    throw new Error(`No Arcade tools found for toolkit "${opts.toolkit}".`);
  }

  if (existsSync(opts.outDir) && !opts.force) {
    throw new Error(
      `Refusing to overwrite ${opts.outDir}. Re-run with --force or choose --out.`,
    );
  }

  await mkdir(path.join(opts.outDir, "src"), { recursive: true });

  const toolkitName = tools[0]?.toolkit?.name ?? snapshot.toolkit;
  const toolkitSlug = slugify(opts.toolkit);
  const packageName =
    opts.packageName ?? `@workflow/integrations-${toolkitSlug}`;

  await writeFile(
    path.join(opts.outDir, "package.json"),
    stableJson({
      name: packageName,
      version: "0.0.1",
      type: "module",
      main: "./dist/index.js",
      types: "./dist/index.d.ts",
      exports: {
        ".": {
          import: "./dist/index.js",
          types: "./dist/index.d.ts",
        },
      },
      scripts: {
        build: "tsc",
        test: "vitest run --passWithNoTests",
        "test:watch": "vitest",
      },
      dependencies: {
        "@workflow/core": "workspace:*",
        zod: "^4.3.6",
      },
      devDependencies: {
        typescript: "^5.7.0",
        vitest: "^3.1.0",
      },
      peerDependencies: {
        zod: "^4.3.6",
      },
    }),
  );

  await writeFile(
    path.join(opts.outDir, "tsconfig.json"),
    stableJson({
      compilerOptions: {
        target: "ES2022",
        module: "ES2022",
        moduleResolution: "bundler",
        declaration: true,
        outDir: "./dist",
        rootDir: "./src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
      },
      include: ["src"],
      exclude: ["node_modules", "dist", "test"],
    }),
  );

  await writeFile(
    path.join(opts.outDir, "src", "arcade.ts"),
    renderArcadeRuntime(toolkitName, toolkitSlug),
  );
  await writeFile(
    path.join(opts.outDir, "src", `${toolkitSlug}.ts`),
    renderToolkit(toolkitName, toolkitSlug, tools),
  );
  await writeFile(
    path.join(opts.outDir, "src", "index.ts"),
    renderIndex(toolkitSlug, tools, {
      includeAtoms: existsSync(path.join(opts.outDir, "src", "atoms.ts")),
    }),
  );

  console.log(
    `Generated ${tools.length} ${toolkitName} tool wrappers in ${opts.outDir}`,
  );
}

async function loadSnapshot(opts: Options): Promise<Snapshot> {
  if (existsSync(opts.snapshotPath)) {
    return parseSnapshot(
      await readFile(opts.snapshotPath, "utf8"),
      opts.toolkit,
    );
  }
  if (opts.noFetch) {
    throw new Error(`Snapshot does not exist: ${opts.snapshotPath}`);
  }

  const apiKey = opts.apiKey ?? process.env.ARCADE_API_KEY;
  if (!apiKey) {
    throw new Error(
      "Set ARCADE_API_KEY or pass --snapshot. Live fetches require Arcade credentials.",
    );
  }

  const tools = await fetchToolkitTools({
    apiKey,
    baseUrl: opts.baseUrl,
    toolkit: opts.toolkit,
  });
  const snapshot = { toolkit: opts.toolkit, tools: normalizeTools(tools) };
  await mkdir(path.dirname(opts.snapshotPath), { recursive: true });
  await writeFile(opts.snapshotPath, stableJson(snapshot));
  return snapshot;
}

async function fetchToolkitTools(args: {
  apiKey: string;
  baseUrl: string;
  toolkit: string;
}): Promise<ToolResponse[]> {
  const first = await fetchToolkitToolsByName(args);
  if (first.length > 0) return first;

  const titleCaseToolkit = pascalCase(args.toolkit);
  if (titleCaseToolkit !== args.toolkit) {
    return fetchToolkitToolsByName({ ...args, toolkit: titleCaseToolkit });
  }
  return first;
}

async function fetchToolkitToolsByName(args: {
  apiKey: string;
  baseUrl: string;
  toolkit: string;
}): Promise<ToolResponse[]> {
  const result: ToolResponse[] = [];
  let offset = 0;
  const limit = 100;

  for (;;) {
    const url = new URL("/v1/tools", args.baseUrl);
    url.searchParams.set("toolkit", args.toolkit);
    url.searchParams.set("limit", String(limit));
    url.searchParams.set("offset", String(offset));

    const response = await fetch(url, {
      headers: { Authorization: `Bearer ${args.apiKey}` },
    });
    if (!response.ok) {
      throw new Error(
        `Arcade GET /v1/tools failed (${response.status}): ${await response.text()}`,
      );
    }

    const page = (await response.json()) as {
      items?: ToolResponse[];
      page_count?: number;
      total_count?: number;
    };
    result.push(...(page.items ?? []));
    offset += limit;
    if (result.length >= (page.total_count ?? result.length)) break;
    if ((page.items ?? []).length === 0) break;
  }

  return result;
}

function renderToolkit(
  toolkitName: string,
  toolkitSlug: string,
  tools: ToolResponse[],
): string {
  const toolkitPascal = pascalCase(toolkitSlug);
  const version = tools[0]?.toolkit?.version;
  const enumSchemas = collectEnumSchemas(toolkitPascal, tools);

  const chunks = [
    GENERATED_HEADER,
    'import type { Action, Atom } from "@workflow/core";\n',
    'import { z } from "zod";\n',
    "import {\n",
    "  type ArcadeToolOptions,\n",
    "  type ArcadeToolResult,\n",
    "  createArcadeToolAction,\n",
    "  createArcadeToolAtom,\n",
    "  type MaybeHandle,\n",
    '} from "./arcade";\n\n',
  ];

  if (version) {
    chunks.push(
      `export const ${constantName(toolkitSlug)}_TOOL_VERSION = ${quote(version)};\n\n`,
    );
  }

  chunks.push(
    `export type ${toolkitPascal}JsonObject = Record<string, unknown>;\n`,
    `export type ${toolkitPascal}ToolOptions = ArcadeToolOptions;\n`,
    `export type ${toolkitPascal}ToolAction<Value = ${toolkitPascal}JsonObject> = Action<ArcadeToolResult<Value>>;\n`,
    `export type ${toolkitPascal}ToolAtom<Value = ${toolkitPascal}JsonObject> = Atom<ArcadeToolResult<Value>>;\n\n`,
    "type Resolvable<T> = MaybeHandle<T>;\n",
    "const jsonObjectSchema: z.ZodType<Record<string, unknown>> = z.object({}).catchall(z.unknown());\n\n",
  );

  for (const enumSchema of enumSchemas.values()) {
    chunks.push(enumSchema.definition, "\n");
  }

  for (const tool of tools) {
    const rendered = renderTool(toolkitName, toolkitPascal, tool);
    chunks.push(rendered.source, "\n");
  }

  chunks.push(renderHelpers(toolkitSlug, toolkitPascal, Boolean(version)));
  return chunks.join("");
}

function renderTool(
  toolkitName: string,
  toolkitPascal: string,
  tool: ToolResponse,
): {
  source: string;
  functionName: string;
  inputTypeName: string;
  optionsTypeName: string;
} {
  const toolBaseName = stripToolkitPrefix(tool.name, toolkitName);
  const functionName = uniqueLowerCamel(toolBaseName);
  const toolTypeName = pascalCase(toolBaseName);
  const inputTypeName = `${toolTypeName}Input`;
  const optionsTypeName = `${toolTypeName}Options`;
  const inputSchemaName = `${functionName}InputSchema`;
  const outputSchema = schemaToZod(tool.output?.value_schema);
  const outputType = schemaToType(tool.output?.value_schema, toolkitPascal);
  const parameters = normalizeParameters(tool.input?.parameters ?? []);
  const qualifiedName = tool.qualified_name;
  const isReadOnly = tool.metadata?.behavior?.read_only === true;
  const isDestructive = tool.metadata?.behavior?.destructive === true;
  const wrapperName =
    isReadOnly && !isDestructive ? "toolkitAtomTool" : "toolkitTool";
  const returnKind = isReadOnly && !isDestructive ? "Atom" : "Action";
  const returnType =
    outputType === `${toolkitPascal}JsonObject`
      ? `${toolkitPascal}Tool${returnKind}`
      : `${toolkitPascal}Tool${returnKind}<${outputType}>`;

  const inputFields =
    parameters.length === 0
      ? `export type ${inputTypeName} = Record<string, never>;\n`
      : `export type ${inputTypeName} = {\n${parameters
          .map((param) => {
            const optional = param.required ? "" : "?";
            return `  ${param.name}${optional}: ${schemaToType(param.value_schema, toolkitPascal)};`;
          })
          .join("\n")}\n};\n`;

  const optionFields =
    parameters.length === 0
      ? `export type ${optionsTypeName} = ${toolkitPascal}ToolOptions;\n`
      : `export type ${optionsTypeName} = ${toolkitPascal}ToolOptions & {\n${parameters
          .map((param) => {
            const optional = param.required ? "" : "?";
            const type = schemaToType(param.value_schema, toolkitPascal);
            const optionType = param.required ? type : `${type} | undefined`;
            return `  ${camelCase(param.name)}${optional}: Resolvable<${optionType}>;`;
          })
          .join("\n")}\n};\n`;

  const schemaFields =
    parameters.length === 0
      ? "const emptyInputSchema = z.object({});\n"
      : `const ${inputSchemaName}: z.ZodType<${inputTypeName}> = z.object({\n${parameters
          .map((param) => {
            const zod = schemaToZod(param.value_schema);
            return `  ${param.name}: ${param.required ? zod : `${zod}.optional()`},`;
          })
          .join("\n")}\n});\n`;

  const inputSchema =
    parameters.length === 0 ? "emptyInputSchema" : inputSchemaName;
  const allParamsOptional =
    parameters.length === 0 || parameters.every((param) => !param.required);
  const inputObject =
    parameters.length === 0
      ? "{}"
      : `{\n${parameters
          .map((param) => `      ${param.name}: opts.${camelCase(param.name)},`)
          .join("\n")}\n    }`;

  return {
    functionName,
    inputTypeName,
    optionsTypeName,
    source: [
      inputFields,
      optionFields,
      schemaFields,
      `export function ${functionName}(opts: ${optionsTypeName}${allParamsOptional ? " = {}" : ""}): ${returnType} {\n`,
      `  return ${wrapperName}({\n`,
      `    toolName: ${quote(qualifiedName)},\n`,
      `    inputSchema: ${inputSchema},\n`,
      `    outputSchema: ${outputSchema},\n`,
      "    opts,\n",
      `    input: ${inputObject},\n`,
      "  });\n",
      "}\n",
    ].join(""),
  };
}

function renderHelpers(
  toolkitSlug: string,
  toolkitPascal: string,
  hasToolkitVersion: boolean,
): string {
  const versionLine = hasToolkitVersion
    ? `    defaultToolVersion: ${constantName(toolkitSlug)}_TOOL_VERSION,\n`
    : "";

  return `function toolkitTool<Input extends Record<string, unknown>, Value>(args: {
  toolName: string;
  inputSchema: z.ZodType<Input>;
  outputSchema: z.ZodType<Value>;
  opts: ${toolkitPascal}ToolOptions;
  input: { [K in keyof Input]: MaybeHandle<Input[K]> | undefined };
}): Action<ArcadeToolResult<Value>> {
  return createArcadeToolAction({
    ...args,
${versionLine}  });
}

function toolkitAtomTool<Input extends Record<string, unknown>, Value>(args: {
  toolName: string;
  inputSchema: z.ZodType<Input>;
  outputSchema: z.ZodType<Value>;
  opts: ${toolkitPascal}ToolOptions;
  input: { [K in keyof Input]: MaybeHandle<Input[K]> | undefined };
}): Atom<ArcadeToolResult<Value>> {
  return createArcadeToolAtom({
    ...args,
${versionLine}  });
}
`;
}

function renderIndex(
  toolkitSlug: string,
  tools: ToolResponse[],
  opts: { includeAtoms: boolean },
): string {
  const toolkitPascal = pascalCase(toolkitSlug);
  const enumSchemas = collectEnumSchemas(toolkitPascal, tools);
  const arcadeTypeExports = new Set<string>([
    "ArcadeAuthorizationResponse",
    "ArcadeAuthorizationStatus",
    "ArcadeCredentials",
    "ArcadeToolOptions",
    "ArcadeToolResult",
    "MaybeHandle",
  ]);
  const arcadeValueExports = new Set<string>([
    "arcade",
    "createArcadeToolAction",
    "createArcadeToolAtom",
  ]);
  const toolkitTypeExports = new Set<string>();
  const toolkitValueExports = new Set<string>();

  toolkitTypeExports.add(`${toolkitPascal}JsonObject`);
  toolkitTypeExports.add(`${toolkitPascal}ToolAction`);
  toolkitTypeExports.add(`${toolkitPascal}ToolAtom`);
  toolkitTypeExports.add(`${toolkitPascal}ToolOptions`);

  for (const enumSchema of enumSchemas.values()) {
    toolkitTypeExports.add(enumSchema.typeName);
    toolkitValueExports.add(enumSchema.schemaName);
  }

  for (const tool of tools) {
    const toolBaseName = stripToolkitPrefix(
      tool.name,
      tools[0]?.toolkit?.name ?? toolkitSlug,
    );
    const toolTypeName = pascalCase(toolBaseName);
    toolkitTypeExports.add(`${toolTypeName}Input`);
    toolkitTypeExports.add(`${toolTypeName}Options`);
    toolkitValueExports.add(uniqueLowerCamel(toolBaseName));
  }

  if (tools[0]?.toolkit?.version) {
    toolkitValueExports.add(`${constantName(toolkitSlug)}_TOOL_VERSION`);
  }

  const chunks = [
    GENERATED_HEADER,
    "export type {\n",
    [...arcadeTypeExports]
      .sort()
      .map((name) => `  ${name},`)
      .join("\n"),
    '\n} from "./arcade";\n',
    "export {\n",
    [...arcadeValueExports]
      .sort()
      .map((name) => `  ${name},`)
      .join("\n"),
    '\n} from "./arcade";\n',
    "export type {\n",
    [...toolkitTypeExports]
      .sort()
      .map((name) => `  ${name},`)
      .join("\n"),
    `\n} from "./${toolkitSlug}";\n`,
    "export {\n",
    [...toolkitValueExports]
      .sort()
      .map((name) => `  ${name},`)
      .join("\n"),
    `\n} from "./${toolkitSlug}";\n`,
  ];

  if (opts.includeAtoms) {
    chunks.push(
      'export type * from "./atoms";\n',
      'export * from "./atoms";\n',
    );
  }

  return chunks.join("");
}

function renderArcadeRuntime(toolkitName: string, toolkitSlug: string): string {
  return `${GENERATED_HEADER}import {
  type Action,
  type Atom,
  action,
  atom,
  type Get,
  type Handle,
  isHandle,
  type RequestIntervention,
  secret,
} from "@workflow/core";
import { type ZodSchema, z } from "zod";

export type ArcadeCredentials = {
  apiKey: string;
  baseUrl: string;
};

export type ArcadeAuthorizationStatus =
  | "not_started"
  | "pending"
  | "completed"
  | "failed";

export type ArcadeAuthorizationResponse = {
  id?: string;
  providerId?: string;
  scopes?: string[];
  status?: ArcadeAuthorizationStatus;
  url?: string;
  userId?: string;
  raw: unknown;
};

export type ArcadeToolResult<Value> = {
  toolName: string;
  toolVersion?: string;
  id?: string;
  executionId?: string;
  executionType?: string;
  status?: string;
  success?: boolean;
  value: Value;
  logs?: unknown[];
  raw: unknown;
};

export type MaybeHandle<T> = Handle<T> | T;

export type ArcadeToolOptions = {
  auth?: Atom<ArcadeCredentials>;
  userId?: MaybeHandle<string>;
  toolVersion?: MaybeHandle<string | undefined>;
  nextUri?: MaybeHandle<string | undefined>;
  includeErrorStacktrace?: MaybeHandle<boolean | undefined>;
  authorize?: MaybeHandle<boolean | undefined>;
  actionName?: string;
  authorizationTitle?: string;
  authorizationDescription?: string;
  authorizationLabel?: string;
};

export type ResolvableInput<T extends Record<string, unknown>> = {
  [K in keyof T]: MaybeHandle<T[K]> | undefined;
};

type CreateArcadeToolArgs<Input extends Record<string, unknown>, Value> = {
  toolName: string;
  defaultToolVersion?: string;
  input: ResolvableInput<Input>;
  inputSchema: ZodSchema<Input>;
  outputSchema: ZodSchema<Value>;
  opts?: ArcadeToolOptions;
};

const ARCADE_API_KEY = secret("ARCADE_API_KEY", envVar("ARCADE_API_KEY"), {
  description: "Arcade project API key used to execute Arcade-hosted tools.",
  errorMessage: "Set ARCADE_API_KEY in the worker environment.",
  internal: true,
});

const ARCADE_USER_ID = secret("ARCADE_USER_ID", envVar("ARCADE_USER_ID"), {
  description: "Arcade user ID used for tool authorization.",
  errorMessage: "Set ARCADE_USER_ID in the worker environment or pass userId to the Arcade tool.",
});

const ARCADE_BASE_URL = "https://api.arcade.dev";

export const arcade = atom<ArcadeCredentials>(
  (get) => ({
    apiKey: get(ARCADE_API_KEY),
    baseUrl: ARCADE_BASE_URL,
  }),
  {
    name: "${camelCase(`${toolkitSlug}-arcade`)}",
    description: "Arcade API credentials resolved from worker secrets.",
    internal: true,
  },
);

const authorizationResponseSchema = z
  .object({
    id: z.string().optional(),
    provider_id: z.string().optional(),
    scopes: z.array(z.string()).optional(),
    status: z.enum(["not_started", "pending", "completed", "failed"]).optional(),
    url: z.string().optional(),
    user_id: z.string().optional(),
  })
  .passthrough();

const responseOutputSchema = z
  .object({
    authorization: authorizationResponseSchema.optional(),
    error: z.unknown().optional(),
    logs: z.array(z.unknown()).optional(),
    value: z.unknown().optional(),
  })
  .passthrough();

const executeToolResponseSchema = z
  .object({
    id: z.string().optional(),
    execution_id: z.string().optional(),
    execution_type: z.string().optional(),
    output: responseOutputSchema.optional(),
    status: z.string().optional(),
    success: z.boolean().optional(),
  })
  .passthrough();

export function createArcadeToolAction<Input extends Record<string, unknown>, Value>(
  args: CreateArcadeToolArgs<Input, Value>,
): Action<ArcadeToolResult<Value>> {
  return action(
    (get, requestIntervention) => runArcadeTool(args, get, requestIntervention),
    { name: args.opts?.actionName ?? defaultActionName(args.toolName) },
  );
}

export function createArcadeToolAtom<Input extends Record<string, unknown>, Value>(
  args: CreateArcadeToolArgs<Input, Value>,
): Atom<ArcadeToolResult<Value>> {
  return atom(
    (get, requestIntervention) => runArcadeTool(args, get, requestIntervention),
    { name: args.opts?.actionName ?? defaultActionName(args.toolName) },
  );
}

async function runArcadeTool<Input extends Record<string, unknown>, Value>(
  args: CreateArcadeToolArgs<Input, Value>,
  get: Get,
  requestIntervention: RequestIntervention,
): Promise<ArcadeToolResult<Value>> {
  const credentials = get(args.opts?.auth ?? arcade);
  const userId = resolveUserId(get, args.opts?.userId);
  const toolVersion = resolveOptional(get, args.opts?.toolVersion) ?? args.defaultToolVersion;
  const input = args.inputSchema.parse(resolveInput(get, args.input));
  const authorize = resolveOptional(get, args.opts?.authorize) ?? true;
  const nextUri = resolveOptional(get, args.opts?.nextUri);

  if (authorize) {
    await authorizeTool({
      credentials,
      toolName: args.toolName,
      toolVersion,
      userId,
      nextUri,
      requestIntervention,
      opts: args.opts,
    });
  }

  const raw = await arcadeRequest({
    credentials,
    path: "/v1/tools/execute",
    body: {
      tool_name: args.toolName,
      tool_version: toolVersion,
      user_id: userId,
      input,
      include_error_stacktrace: resolveOptional(get, args.opts?.includeErrorStacktrace),
    },
  });
  const parsed = executeToolResponseSchema.parse(raw);
  const output = parsed.output;
  if (output?.authorization && output.authorization.status !== "completed") {
    throw new Error(\`Arcade authorization is required for \${args.toolName}.\`);
  }
  if (parsed.success === false || output?.error) {
    throw new Error(\`Arcade \${args.toolName} failed: \${formatArcadeError(output?.error)}\`);
  }

  return {
    toolName: args.toolName,
    toolVersion,
    id: parsed.id,
    executionId: parsed.execution_id,
    executionType: parsed.execution_type,
    status: parsed.status,
    success: parsed.success,
    value: args.outputSchema.parse(output?.value),
    logs: output?.logs,
    raw,
  };
}

async function authorizeTool(args: {
  credentials: ArcadeCredentials;
  toolName: string;
  toolVersion?: string;
  userId: string;
  nextUri?: string;
  requestIntervention: RequestIntervention;
  opts?: ArcadeToolOptions;
}): Promise<void> {
  const raw = await arcadeRequest({
    credentials: args.credentials,
    path: "/v1/tools/authorize",
    body: {
      tool_name: args.toolName,
      tool_version: args.toolVersion,
      user_id: args.userId,
      next_uri: args.nextUri,
    },
  });
  let authorization = toAuthorizationResponse(raw);
  if (authorization.status === "completed") return;
  if (!authorization.url) {
    throw new Error(\`Arcade did not return an authorization URL for \${args.toolName}.\`);
  }

  args.requestIntervention(
    \`arcade-\${sanitizeInterventionKey(args.toolName)}-authorization\`,
    z.object({ ok: z.boolean().optional() }).passthrough(),
    {
      title: args.opts?.authorizationTitle ?? \`Authorize \${args.toolName.replace(/^${escapeRegExp(toolkitName)}\\\\./, "${toolkitName} ")}\`,
      description:
        args.opts?.authorizationDescription ??
        "Open Arcade authorization, approve access, then resolve this intervention to continue the workflow.",
      action: {
        type: "open_url",
        url: authorization.url,
        label: args.opts?.authorizationLabel ?? "Authorize in Arcade",
      },
      actionUrl: authorization.url,
    },
  );

  if (!authorization.id) return;
  authorization = await checkAuthorizationStatus(args.credentials, authorization.id);
  if (authorization.status !== "completed") {
    throw new Error(
      \`Arcade authorization for \${args.toolName} is \${authorization.status ?? "not completed"}.\`,
    );
  }
}

async function checkAuthorizationStatus(
  credentials: ArcadeCredentials,
  id: string,
): Promise<ArcadeAuthorizationResponse> {
  const url = new URL("/v1/auth/status", credentials.baseUrl);
  url.searchParams.set("id", id);
  url.searchParams.set("wait", "1");
  const response = await fetch(url, {
    headers: { Authorization: \`Bearer \${credentials.apiKey}\` },
  });
  if (!response.ok) {
    throw new Error(
      \`Arcade GET /v1/auth/status failed (\${response.status}): \${await response.text()}\`,
    );
  }
  return toAuthorizationResponse(await response.json());
}

async function arcadeRequest(args: {
  credentials: ArcadeCredentials;
  path: string;
  body: Record<string, unknown>;
}): Promise<unknown> {
  const response = await fetch(new URL(args.path, args.credentials.baseUrl), {
    method: "POST",
    headers: {
      Authorization: \`Bearer \${args.credentials.apiKey}\`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(compact(args.body)),
  });
  if (!response.ok) {
    throw new Error(
      \`Arcade \${args.path} failed (\${response.status}): \${await response.text()}\`,
    );
  }
  return response.json();
}

function toAuthorizationResponse(raw: unknown): ArcadeAuthorizationResponse {
  const parsed = authorizationResponseSchema.parse(raw);
  return {
    id: parsed.id,
    providerId: parsed.provider_id,
    scopes: parsed.scopes,
    status: parsed.status,
    url: parsed.url,
    userId: parsed.user_id,
    raw,
  };
}

function resolveInput<Input extends Record<string, unknown>>(
  get: Get,
  input: ResolvableInput<Input>,
): Input {
  const resolved: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(input)) {
    if (value === undefined) continue;
    const item = isHandle(value) ? get(value) : value;
    if (item !== undefined) resolved[key] = item;
  }
  return resolved as Input;
}

function resolveUserId(get: Get, userId: MaybeHandle<string> | undefined): string {
  return userId === undefined ? get(ARCADE_USER_ID) : resolve(get, userId);
}

function resolve<T>(get: Get, value: MaybeHandle<T>): T {
  return isHandle(value) ? get(value) : value;
}

function resolveOptional<T>(
  get: Get,
  value: MaybeHandle<T> | undefined,
): T | undefined {
  return value === undefined ? undefined : resolve(get, value);
}

function compact<T extends Record<string, unknown>>(value: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(value).filter(([, item]) => item !== undefined),
  ) as Partial<T>;
}

function defaultActionName(toolName: string): string {
  return toolName.replace(/^[^.]+\\./, "").replace(/^[A-Z]/, (value) => value.toLowerCase());
}

function sanitizeInterventionKey(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function formatArcadeError(error: unknown): string {
  if (typeof error === "string") return error;
  if (error && typeof error === "object" && "message" in error) {
    const message = (error as { message?: unknown }).message;
    if (typeof message === "string") return message;
  }
  return JSON.stringify(error ?? "unknown error");
}

function envVar(name: string): string | undefined {
  const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process
    ?.env;
  return env?.[name];
}
`;
}

function collectEnumSchemas(
  toolkitPascal: string,
  tools: ToolResponse[],
): Map<string, { typeName: string; schemaName: string; definition: string }> {
  const schemas = new Map<
    string,
    { typeName: string; schemaName: string; definition: string }
  >();
  const usedTypeNames = new Set<string>();

  for (const tool of tools) {
    const parameters = normalizeParameters(tool.input?.parameters ?? []);
    for (const parameter of parameters) {
      const values = parameter.value_schema.enum;
      if (!values || values.length === 0) continue;
      const key = [...values].sort().join("\0");
      if (schemas.has(key)) continue;

      const baseTypeName = `${toolkitPascal}${pascalCase(parameter.name)}`;
      let typeName = baseTypeName;
      if (usedTypeNames.has(typeName)) {
        typeName = `${toolkitPascal}${pascalCase(tool.name)}${pascalCase(parameter.name)}`;
      }
      let suffix = 2;
      while (usedTypeNames.has(typeName)) {
        typeName = `${baseTypeName}${suffix}`;
        suffix += 1;
      }
      usedTypeNames.add(typeName);

      const schemaName = `${lowerFirst(typeName)}Schema`;
      schemas.set(key, {
        typeName,
        schemaName,
        definition: `export const ${schemaName} = z.enum([${values
          .map(quote)
          .join(
            ", ",
          )}]);\nexport type ${typeName} = z.infer<typeof ${schemaName}>;\n`,
      });
    }
  }

  return schemas;
}

function schemaToType(
  schema: ValueSchema | undefined,
  toolkitPascal: string,
): string {
  if (!schema) return `${toolkitPascal}JsonObject`;
  if (schema.enum && schema.enum.length > 0) {
    return schema.enum.map(quote).join(" | ");
  }

  switch (schema.val_type.toLowerCase()) {
    case "string":
    case "str":
      return "string";
    case "integer":
    case "int":
    case "number":
    case "float":
      return "number";
    case "boolean":
    case "bool":
      return "boolean";
    case "array":
    case "list":
      return `${primitiveType(schema.inner_val_type)}[]`;
    case "object":
    case "dict":
    case "json":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function schemaToZod(schema: ValueSchema | undefined): string {
  if (!schema) return "jsonObjectSchema";
  if (schema.enum && schema.enum.length > 0) {
    return `z.enum([${schema.enum.map(quote).join(", ")}])`;
  }

  switch (schema.val_type.toLowerCase()) {
    case "string":
    case "str":
      return "z.string()";
    case "integer":
    case "int":
      return "z.number().int()";
    case "number":
    case "float":
      return "z.number()";
    case "boolean":
    case "bool":
      return "z.boolean()";
    case "array":
    case "list":
      return `z.array(${primitiveZod(schema.inner_val_type)})`;
    case "object":
    case "dict":
    case "json":
      return "jsonObjectSchema";
    default:
      return "z.unknown()";
  }
}

function primitiveType(value: string | undefined): string {
  switch ((value ?? "unknown").toLowerCase()) {
    case "string":
    case "str":
      return "string";
    case "integer":
    case "int":
    case "number":
    case "float":
      return "number";
    case "boolean":
    case "bool":
      return "boolean";
    case "object":
    case "dict":
    case "json":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function primitiveZod(value: string | undefined): string {
  switch ((value ?? "unknown").toLowerCase()) {
    case "string":
    case "str":
      return "z.string()";
    case "integer":
    case "int":
      return "z.number().int()";
    case "number":
    case "float":
      return "z.number()";
    case "boolean":
    case "bool":
      return "z.boolean()";
    case "object":
    case "dict":
    case "json":
      return "jsonObjectSchema";
    default:
      return "z.unknown()";
  }
}

function normalizeTools(tools: ToolResponse[]): ToolResponse[] {
  return [...tools].sort((left, right) =>
    (left.fully_qualified_name ?? left.qualified_name).localeCompare(
      right.fully_qualified_name ?? right.qualified_name,
    ),
  );
}

function normalizeParameters(parameters: ToolParameter[]): ToolParameter[] {
  return [...parameters].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
}

function parseSnapshot(value: string, fallbackToolkit: string): Snapshot {
  const parsed = JSON.parse(value) as Snapshot | ToolResponse[];
  if (Array.isArray(parsed)) return { toolkit: fallbackToolkit, tools: parsed };
  return parsed;
}

function parseArgs(args: string[]): Options {
  if (args.includes("--help") || args.includes("-h")) {
    console.log(`Usage:
  pnpm arcade:generate <toolkit> [--out <dir>] [--snapshot <file>] [--force]

Examples:
  pnpm arcade:generate gmail --out packages/integrations/gmail-generated
  pnpm arcade:generate gmail --snapshot .context/arcade-gmail-tools.json --force

The first run fetches /v1/tools from Arcade and writes the snapshot. Later runs
from the same snapshot are deterministic.`);
    process.exit(0);
  }

  const toolkit = args.find((arg) => !arg.startsWith("-"));
  if (!toolkit) throw new Error("Missing toolkit name, for example: gmail");

  const getFlag = (name: string): string | undefined => {
    const index = args.indexOf(name);
    return index === -1 ? undefined : args[index + 1];
  };

  const toolkitSlug = slugify(toolkit);
  return {
    toolkit,
    outDir:
      getFlag("--out") ?? path.join("packages", "integrations", toolkitSlug),
    snapshotPath:
      getFlag("--snapshot") ??
      path.join(".context", `arcade-${toolkitSlug}-tools.json`),
    apiKey: getFlag("--api-key"),
    baseUrl: getFlag("--base-url") ?? "https://api.arcade.dev",
    packageName: getFlag("--package-name"),
    force: args.includes("--force"),
    noFetch: args.includes("--no-fetch"),
  };
}

function stableJson(value: unknown): string {
  return `${JSON.stringify(sortJson(value), null, 2)}\n`;
}

function sortJson(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortJson);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, item]) => [key, sortJson(item)]),
  );
}

function slugify(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function pascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+|(?=[A-Z])/)
    .filter(Boolean)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join("");
}

function camelCase(value: string): string {
  return lowerFirst(pascalCase(value));
}

function uniqueLowerCamel(value: string): string {
  const result = camelCase(value);
  return result.length === 0 ? "tool" : result;
}

function lowerFirst(value: string): string {
  return value.slice(0, 1).toLowerCase() + value.slice(1);
}

function constantName(value: string): string {
  return slugify(value).replace(/-/g, "_").toUpperCase();
}

function stripToolkitPrefix(value: string, toolkitName: string): string {
  return value.replace(new RegExp(`^${escapeRegExp(toolkitName)}\\.`), "");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function quote(value: string): string {
  return JSON.stringify(value);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
